service: serverless-template-ts

frameworkVersion: '2'

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'
    excludeFiles: src/**/*.test.js


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-northeast-1

  patterns:
    - '!node_modules/**'

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello

plugins:
  - serverless-webpack
